<?php 
$pageTitle = "Games";
$filename = basename(__FILE__);
require_once('header.php');
$createTime = date('Y-m-d',filectime($filename));?>
	<header><?php echo ("Text generated by <EM>PHP</EM>.");?></header>
	<main>
	<?php $dir=dirname(__FILE__).'/games';
		$file_arr=scandir($dir,0);
		
	if(!empty($file_arr)){
		$arr_js=array();
	?>
		<p class="in2em">Games php:小游戏 </p>
		<ul class="decimal">
			<?php foreach($file_arr as $k=>$v){
				if( $v == '.'|| $v == '..'){continue;}
				if(is_file($dir.DIRECTORY_SEPARATOR.$v)){
					$url = 'games/'.$v;
				}else{
					$url = 'games/'.$v;
				}
			?>
			<li>
				<a href="<?php echo $url; ?>" target="_blank"><?php echo $v;?></a>
			</li>
			<?php }?>
		</ul>
	<?php }?>
	</main>
<?php include_once 'footer.php'; ?>