<?php 
$pageTitle = "JavaScript设计模式";
$filename = basename(__FILE__);
require_once('header.php');
$createTime = date('Y-m-d',filectime($filename));?>
	<header><?php echo ("Text generated by <EM>PHP</EM>.");?></header>
	<main>
	<?php $dir=dirname(__FILE__).'/javascript ';
	$file_arr=scandir($dir,0);
	if(!empty($file_arr)){
		$arr_js=array();
	?>
	<p class="in2em">JavaScript设计模式</p>
	<ul class="decimal">
		<?php foreach($file_arr as $k=>$v){ 
			if(preg_match('/\d+/',$v,$m)){ $arr_js[$m[0]]=$v; }
		}
		for($i=1;$i<count($arr_js);$i++){
		?>
		<li>
			<a href="<?php echo 'javascript/'.$arr_js[$i];?>" target="_blank"><?php echo $arr_js[$i];?></a>
		</li>
		<?php }?>
	</ul>
	<?php }?>
	</main>
<?php include_once 'footer.php'; ?>
