<?php //前端不显示在导航中的页面
$not_show_display=array(
	'.gitignore',
	'.htaccess',
	'index.php',
	'navbar.php',
	'un.php',
	'config.php',
	'footer.php',
	'test.php',
	'file.txt',
	'file.csv',
	'upload_file.php',
	'framework7.php',
	'favicon.ico',
	'readme.txt',
	'xbug.sublime-workspace',
	'header.php',
	'Readme.md'
);