SELECT
	T.TABLE_SCHEMA AS 'DB Name',
	T.TABLE_NAME AS 'Table Name',
	T.TABLE_TYPE 'Table Type',
	T.`ENGINE` 'Engine',
	C.ORDINAL_POSITION 'No.',
	C.COLUMN_NAME 'Field Name',
	C.COLUMN_TYPE 'Column Type',
	C.IS_NULLABLE 'Is Null',
	C.COLUMN_KEY 'Key',
	C.EXTRA 'Is Increase',
	C.CHARACTER_SET_NAME 'Charset',
	C.COLUMN_COMMENT 'Field Comment'
FROM
	`COLUMNS` AS C
INNER JOIN `TABLES` AS T ON C.TABLE_SCHEMA = T.TABLE_SCHEMA
AND C.TABLE_NAME = T.TABLE_NAME
WHERE
	T.TABLE_SCHEMA = 'genec1' AND T.TABLE_NAME != 'a'
ORDER BY T.TABLE_NAME ASC, C.COLUMN_NAME ASC